/**
 *
 *  NewsCtrl.cc
 *  This file is generated by drogon_ctl
 *
 */

#include "NewsCtrl.h"

#include <string>

void NewsCtrl::getOne(const HttpRequestPtr& req,
					  std::function<void(const HttpResponsePtr&)>&& callback,
					  News::PrimaryKeyType&& id) {
	NewsCtrlBase::getOne(req, std::move(callback), std::move(id));
}

void NewsCtrl::get(const HttpRequestPtr& req,
				   std::function<void(const HttpResponsePtr&)>&& callback) {
	NewsCtrlBase::get(req, std::move(callback));
}
