
/**
 *
 *  NewsCtrlBase.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl automatically.
 *  Users should implement business logic in the derived class.
 */

#include "NewsCtrlBase.h"

#include <string>

void NewsCtrlBase::getOne(
	const HttpRequestPtr& req,
	std::function<void(const HttpResponsePtr&)>&& callback,
	News::PrimaryKeyType&& id) {
	auto dbClientPtr = getDbClient();
	auto callbackPtr =
		std::make_shared<std::function<void(const HttpResponsePtr&)>>(
			std::move(callback));
	drogon::orm::Mapper<News> mapper(dbClientPtr);
	mapper.findByPrimaryKey(
		id,
		[req, callbackPtr, this](News r) {
			(*callbackPtr)(HttpResponse::newHttpJsonResponse(makeJson(req, r)));
		},
		[callbackPtr](const DrogonDbException& e) {
			const drogon::orm::UnexpectedRows* s =
				dynamic_cast<const drogon::orm::UnexpectedRows*>(&e.base());
			if (s) {
				auto resp = HttpResponse::newHttpResponse();
				resp->setStatusCode(k404NotFound);
				(*callbackPtr)(resp);
				return;
			}
			LOG_ERROR << e.base().what();
			Json::Value ret;
			ret["error"] = "database error";
			auto resp = HttpResponse::newHttpJsonResponse(ret);
			resp->setStatusCode(k500InternalServerError);
			(*callbackPtr)(resp);
		});
}

void NewsCtrlBase::get(const HttpRequestPtr& req,
					   std::function<void(const HttpResponsePtr&)>&& callback) {
	auto dbClientPtr = getDbClient();
	drogon::orm::Mapper<News> mapper(dbClientPtr);
	auto& parameters = req->parameters();
	auto iter = parameters.find("sort");
	if (iter != parameters.end()) {
		auto sortFields = drogon::utils::splitString(iter->second, ",");
		for (auto& field : sortFields) {
			if (field.empty()) continue;
			if (field[0] == '+') {
				field = field.substr(1);
				mapper.orderBy(field, SortOrder::ASC);
			} else if (field[0] == '-') {
				field = field.substr(1);
				mapper.orderBy(field, SortOrder::DESC);
			} else {
				mapper.orderBy(field, SortOrder::ASC);
			}
		}
	}
	iter = parameters.find("offset");
	if (iter != parameters.end()) {
		try {
			auto offset = std::stoll(iter->second);
			mapper.offset(offset);
		} catch (...) {
			auto resp = HttpResponse::newHttpResponse();
			resp->setStatusCode(k400BadRequest);
			callback(resp);
			return;
		}
	}
	iter = parameters.find("limit");
	if (iter != parameters.end()) {
		try {
			auto limit = std::stoll(iter->second);
			mapper.limit(limit);
		} catch (...) {
			auto resp = HttpResponse::newHttpResponse();
			resp->setStatusCode(k400BadRequest);
			callback(resp);
			return;
		}
	}
	auto callbackPtr =
		std::make_shared<std::function<void(const HttpResponsePtr&)>>(
			std::move(callback));
	auto jsonPtr = req->jsonObject();
	if (jsonPtr && jsonPtr->isMember("filter")) {
		try {
			auto criteria = makeCriteria((*jsonPtr)["filter"]);
			mapper.findBy(
				criteria,
				[req, callbackPtr, this](const std::vector<News>& v) {
					Json::Value ret;
					ret.resize(0);
					for (auto& obj : v) {
						ret.append(makeJson(req, obj));
					}
					(*callbackPtr)(HttpResponse::newHttpJsonResponse(ret));
				},
				[callbackPtr](const DrogonDbException& e) {
					LOG_ERROR << e.base().what();
					Json::Value ret;
					ret["error"] = "database error";
					auto resp = HttpResponse::newHttpJsonResponse(ret);
					resp->setStatusCode(k500InternalServerError);
					(*callbackPtr)(resp);
				});
		} catch (const std::exception& e) {
			LOG_ERROR << e.what();
			Json::Value ret;
			ret["error"] = e.what();
			auto resp = HttpResponse::newHttpJsonResponse(ret);
			resp->setStatusCode(k400BadRequest);
			(*callbackPtr)(resp);
			return;
		}
	} else {
		mapper.findAll(
			[req, callbackPtr, this](const std::vector<News>& v) {
				Json::Value ret;
				ret.resize(0);
				for (auto& obj : v) {
					ret.append(makeJson(req, obj));
				}
				(*callbackPtr)(HttpResponse::newHttpJsonResponse(ret));
			},
			[callbackPtr](const DrogonDbException& e) {
				LOG_ERROR << e.base().what();
				Json::Value ret;
				ret["error"] = "database error";
				auto resp = HttpResponse::newHttpJsonResponse(ret);
				resp->setStatusCode(k500InternalServerError);
				(*callbackPtr)(resp);
			});
	}
}

NewsCtrlBase::NewsCtrlBase()
	: RestfulController({"id", "title", "original_text", "source_url"}) {
	/**
	 * The items in the vector are aliases of column names in the table.
	 * if one item is set to an empty string, the related column is not sent
	 * to clients.
	 */
	enableMasquerading({
		"id",			  // the alias for the id column.
		"title",		  // the alias for the title column.
		"original_text",  // the alias for the original_text column.
		"source_url"	  // the alias for the source_url column.
	});
}
